using Enterprise.API.Security.Constants;
using Microsoft.AspNetCore.Authentication.JwtBearer;

namespace Enterprise.API.Security.Options;

public class JwtBearerTokenOptions
{
    /// <summary>
    /// The API is configured to trust tokens generated by the identity provider / security token service at this URL:
    /// </summary>
    public string Authority { get; set; }

    /// <summary>
    /// The audience is a token claim that contains the name of the application it is meant for.
    /// This was created by Microsoft and is not part of the OAuth2 standard.
    /// </summary>
    public string Audience { get; set; }

    /// <summary>
    /// The claim used for the name of the logged in user.
    /// </summary>
    public string? NameClaimType { get; set; }

    /// <summary>
    /// A custom delegate that allows for complete customization of JwtBearerOptions.
    /// NOTE: if this is provided, all the default configuration is ignored.
    /// </summary>
    public Action<JwtBearerOptions>? ConfigureJwtBearerOptions { get; set; }

    public JwtBearerTokenOptions()
    {
        Authority = string.Empty;
        Audience = string.Empty;
        NameClaimType = SecurityConstants.DefaultJwtNameClaimType;
        ConfigureJwtBearerOptions = null;
    }
}